name: Terraform Plan

on: push

jobs:
  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Instalar Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0  # Altere para a versão necessária

    - name: Configurar Credenciais AWS
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      run: echo "Credenciais configuradas"

    - name: Inicializar Terraform
      run: terraform init

    - name: Verificar Formatação
      run: terraform fmt -check

    - name: Validar Código Terraform
      run: terraform validate

    - name: Executar Terraform Plan
      run: terraform plan
