name: Terraform Destroy
on: workflow_dispatch
env:
  aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}} 
  aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}} 
  TF_VAR_aws_key_pub: ${{secrets.TF_VAR_aws_key_pub}}

jobs:
  terraform_Destroy:
    name: Terraform Destroy
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Terraform Destroy
      run: |
        terraform init
        terraform destroy -auto-approve
